<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Cafe;

class CafeSeeder extends Seeder
{
    public function run()
    {
        $cafes = [

            [
                "name" => "Cuervo Café",
                "address" => "El Salvador 4580, Palermo",
                "lat" => -34.586574,
                "lng" => -58.430129,
                "description" => "Café de especialidad con tuestes propios y ambiente minimalista.",
                "average_rating" => 4.8,
                "opening_hours" => json_encode([
                    "lunes" => "08:00-20:00",
                    "martes" => "08:00-20:00",
                    "miercoles" => "08:00-20:00",
                    "jueves" => "08:00-20:00",
                    "viernes" => "08:00-21:00",
                    "sabado" => "09:00-21:00",
                    "domingo" => "09:00-20:00",
                ]),
                "coffee_types" => json_encode(["Colombiano","Etiopé","Blend Propietario"]),
                "milk_options" => json_encode(["Avena","Almendra","Sin lactosa"]),
                "features" => json_encode(["wifi","musica","pet_friendly"]),
            ],[
                "name" => "Cuervo Café- Chacarita",
                "address" => "El Salvador 4580, Palermo",
                "lat" => -34.586714,
                "lng" => -58.450061,
                "description" => "Café de especialidad con tuestes propios y ambiente minimalista.",
                "average_rating" => 4.8,
                "opening_hours" => json_encode([
                    "lunes" => "08:00-20:00",
                    "martes" => "08:00-20:00",
                    "miercoles" => "08:00-20:00",
                    "jueves" => "08:00-20:00",
                    "viernes" => "08:00-21:00",
                    "sabado" => "09:00-21:00",
                    "domingo" => "09:00-20:00",
                ]),
                "coffee_types" => json_encode(["Colombiano","Etiopé","Blend Propietario"]),
                "milk_options" => json_encode(["Avena","Almendra","Sin lactosa"]),
                "features" => json_encode(["wifi","musica","pet_friendly"]),
            ],

            [
                "name" => "LAB Tostadores de Café",
                "address" => "Humboldt 1542, Palermo",
                "lat" => -34.582148,
                "lng" => -58.438760,
                "description" => "Tostadores pioneros del café de especialidad.",
                "average_rating" => 4.9,
                "opening_hours" => json_encode([
                    "lunes" => "08:00-20:00",
                    "martes" => "08:00-20:00",
                    "miercoles" => "08:00-20:00",
                    "jueves" => "08:00-20:00",
                    "viernes" => "08:00-21:00",
                    "sabado" => "09:00-21:00",
                    "domingo" => "09:00-19:00",
                ]),
                "coffee_types" => json_encode(["Colombiano","Guatemalteco","Blend Propietario"]),
                "milk_options" => json_encode(["Avena","Soja","Almendra"]),
                "features" => json_encode(["wifi","terraza","musica"]),
            ],

            [
                "name" => "Barrio Cafetero",
                "address" => "Guardia Vieja 3559, Almagro",
                "lat" => -34.603091,
                "lng" => -58.418189,
                "description" => "Café pequeño de barrio con alto nivel de extracción.",
                "average_rating" => 4.7,
                "opening_hours" => json_encode([
                    "lunes" => "08:00-18:00",
                    "martes" => "08:00-18:00",
                    "miercoles" => "08:00-18:00",
                    "jueves" => "08:00-18:00",
                    "viernes" => "08:00-18:00",
                    "sabado" => "09:00-18:00",
                ]),
                "coffee_types" => json_encode(["Etiopé","Colombiano"]),
                "milk_options" => json_encode(["Avena","Sin lactosa"]),
                "features" => json_encode(["wifi","pet_friendly"]),
            ],

            [
                "name" => "Negro Café",
                "address" => "Suipacha 637, Microcentro",
                "lat" => -34.602988,
                "lng" => -58.377200,
                "description" => "Cadena moderna con café de especialidad.",
                "average_rating" => 4.5,
                "opening_hours" => json_encode([
                    "lunes" => "07:30-19:00",
                    "martes" => "07:30-19:00",
                    "miercoles" => "07:30-19:00",
                    "jueves" => "07:30-19:00",
                    "viernes" => "07:30-19:00",
                ]),
                "coffee_types" => json_encode(["Colombiano","Blend Propietario"]),
                "milk_options" => json_encode(["Avena","Soja"]),
                "features" => json_encode(["wifi"]),
            ],

            [
                "name" => "Fuego Tostadores",
                "address" => "Roseti 93, Chacarita",
                "lat" => -34.587820,
                "lng" => -58.448889,
                "description" => "Tostadora boutique con granos latinoamericanos.",
                "average_rating" => 4.9,
                "opening_hours" => json_encode([
                    "lunes" => "08:00-19:00",
                    "martes" => "08:00-19:00",
                    "miercoles" => "08:00-19:00",
                    "jueves" => "08:00-19:00",
                    "viernes" => "08:00-20:00",
                    "sabado" => "09:00-20:00",
                ]),
                "coffee_types" => json_encode(["Guatemalteco","Colombiano","Etiopé"]),
                "milk_options" => json_encode(["Avena","Almendra","Sin lactosa"]),
                "features" => json_encode(["wifi","musica","terraza"]),
            ],

            [
                "name" => "Lattente",
                "address" => "Thames 1891, Palermo Soho",
                "lat" => -34.587291,
                "lng" => -58.432012,
                "description" => "Pioneros del café de especialidad en Buenos Aires.",
                "average_rating" => 4.8,
                "opening_hours" => json_encode([
                    "lunes" => "08:00-20:00",
                    "martes" => "08:00-20:00",
                    "miercoles" => "08:00-20:00",
                    "jueves" => "08:00-20:00",
                    "viernes" => "08:00-21:00",
                    "sabado" => "09:00-21:00",
                ]),
                "coffee_types" => json_encode(["Etiopé","Blend Propietario"]),
                "milk_options" => json_encode(["Avena","Almendra"]),
                "features" => json_encode(["wifi","pet_friendly"]),
            ],

            [
                "name" => "Dos Escudos",
                "address" => "Juncal 907, Recoleta",
                "lat" => -34.595912,
                "lng" => -58.383174,
                "description" => "Café clásico renovado con granos de especialidad.",
                "average_rating" => 4.3,
                "opening_hours" => json_encode([
                    "lunes" => "08:00-21:00",
                    "martes" => "08:00-21:00",
                    "miercoles" => "08:00-21:00",
                    "jueves" => "08:00-21:00",
                    "viernes" => "08:00-22:00",
                    "sabado" => "09:00-22:00",
                ]),
                "coffee_types" => json_encode(["Colombiano","Guatemalteco"]),
                "milk_options" => json_encode(["Soja","Sin lactosa"]),
                "features" => json_encode(["musica","terraza"]),
            ],

            [
                "name" => "Full City Coffee House",
                "address" => "Thames 1535, Palermo",
                "lat" => -34.591802,
                "lng" => -58.430991,
                "description" => "Café de especialidad con raíces colombianas.",
                "average_rating" => 4.7,
                "opening_hours" => json_encode([
                    "lunes" => "08:00-20:00",
                    "martes" => "08:00-20:00",
                    "miercoles" => "08:00-20:00",
                    "jueves" => "08:00-20:00",
                    "viernes" => "08:00-21:00",
                    "sabado" => "09:00-21:00",
                ]),
                "coffee_types" => json_encode(["Colombiano","Blend Propietario"]),
                "milk_options" => json_encode(["Avena","Almendra"]),
                "features" => json_encode(["wifi","pet_friendly","musica"]),
            ],

            [
                "name" => "The Shelter Coffee",
                "address" => "Estados Unidos 465, San Telmo",
                "lat" => -34.621223,
                "lng" => -58.372992,
                "description" => "Café de especialidad con estética industrial.",
                "average_rating" => 4.6,
                "opening_hours" => json_encode([
                    "martes" => "09:00-19:00",
                    "miercoles" => "09:00-19:00",
                    "jueves" => "09:00-19:00",
                    "viernes" => "09:00-20:00",
                    "sabado" => "09:00-20:00",
                    "domingo" => "10:00-18:00",
                ]),
                "coffee_types" => json_encode(["Guatemalteco","Colombiano"]),
                "milk_options" => json_encode(["Avena","Sin lactosa"]),
                "features" => json_encode(["wifi","musica"]),
            ],
            [
    "name" => "Coffee Town",
    "address" => "Bolívar 976, San Telmo",
    "lat" => -34.617924,
    "lng" => -58.370355,
    "description" => "Café de especialidad dentro del Mercado de San Telmo, con amplia variedad de orígenes.",
    "average_rating" => 4.5,
    "opening_hours" => json_encode([
        "lunes" => "09:00-20:00",
        "martes" => "09:00-20:00",
        "miercoles" => "09:00-20:00",
        "jueves" => "09:00-20:00",
        "viernes" => "09:00-20:00",
        "sabado" => "09:00-20:00",
        "domingo" => "09:00-20:00",
    ]),
    "coffee_types" => json_encode(["Etiopé","Colombiano"]),
    "milk_options" => json_encode(["Avena","Almendra","Sin lactosa"]),
    "features" => json_encode(["wifi","musica"]),
],

[
    "name" => "Vive Café",
    "address" => "Cabildo 1950, Belgrano",
    "lat" => -34.562482,
    "lng" => -58.456781,
    "description" => "Café luminoso con estilo moderno y granos latinoamericanos de primera calidad.",
    "average_rating" => 4.6,
    "opening_hours" => json_encode([
        "lunes" => "08:00-21:00",
        "martes" => "08:00-21:00",
        "miercoles" => "08:00-21:00",
        "jueves" => "08:00-21:00",
        "viernes" => "08:00-22:00",
        "sabado" => "09:00-22:00",
        "domingo" => "09:00-20:00",
    ]),
    "coffee_types" => json_encode(["Guatemalteco","Blend Propietario"]),
    "milk_options" => json_encode(["Avena","Soja"]),
    "features" => json_encode(["wifi","pet_friendly","terraza"]),
],

[
    "name" => "Cigaló Café",
    "address" => "Charcas 3742, Palermo",
    "lat" => -34.590915,
    "lng" => -58.415712,
    "description" => "Café pequeño y acogedor, famoso por su latte arte y productos artesanales.",
    "average_rating" => 4.7,
    "opening_hours" => json_encode([
        "martes" => "09:00-19:00",
        "miercoles" => "09:00-19:00",
        "jueves" => "09:00-19:00",
        "viernes" => "09:00-20:00",
        "sabado" => "09:00-20:00",
        "domingo" => "10:00-18:00",
    ]),
    "coffee_types" => json_encode(["Colombiano","Guatemalteco"]),
    "milk_options" => json_encode(["Avena","Almendra"]),
    "features" => json_encode(["wifi","musica"]),
],

[
    "name" => "Yeite Café",
    "address" => "Thames 1905, Palermo",
    "lat" => -34.588140,
    "lng" => -58.431945,
    "description" => "Café de especialidad con panificación propia y estilo nórdico.",
    "average_rating" => 4.8,
    "opening_hours" => json_encode([
        "lunes" => "09:00-19:00",
        "martes" => "09:00-19:00",
        "miercoles" => "09:00-19:00",
        "jueves" => "09:00-19:00",
        "viernes" => "09:00-19:00",
        "sabado" => "09:00-19:00",
        "domingo" => "10:00-18:00",
    ]),
    "coffee_types" => json_encode(["Etiopé","Blend Propietario"]),
    "milk_options" => json_encode(["Avena","Sin lactosa"]),
    "features" => json_encode(["wifi","terraza"]),
],

[
    "name" => "Bonafide Select",
    "address" => "Arenales 1600, Recoleta",
    "lat" => -34.595111,
    "lng" => -58.395712,
    "description" => "Versión premium de Bonafide con selección de cafés especiales.",
    "average_rating" => 4.2,
    "opening_hours" => json_encode([
        "lunes" => "08:00-21:00",
        "martes" => "08:00-21:00",
        "miercoles" => "08:00-21:00",
        "jueves" => "08:00-21:00",
        "viernes" => "08:00-22:00",
        "sabado" => "09:00-22:00",
        "domingo" => "09:00-20:00",
    ]),
    "coffee_types" => json_encode(["Colombiano","Guatemalteco"]),
    "milk_options" => json_encode(["Avena","Soja"]),
    "features" => json_encode(["musica"]),
],

[
    "name" => "Cocu Boulangerie",
    "address" => "Malabia 1510, Palermo",
    "lat" => -34.589502,
    "lng" => -58.431021,
    "description" => "Panadería francesa con café de especialidad en un ambiente rústico chic.",
    "average_rating" => 4.5,
    "opening_hours" => json_encode([
        "lunes" => "08:00-20:00",
        "martes" => "08:00-20:00",
        "miercoles" => "08:00-20:00",
        "jueves" => "08:00-20:00",
        "viernes" => "08:00-20:00",
        "sabado" => "08:00-20:00",
        "domingo" => "09:00-19:00",
    ]),
    "coffee_types" => json_encode(["Blend Propietario"]),
    "milk_options" => json_encode(["Avena","Almendra"]),
    "features" => json_encode(["wifi","pet_friendly"]),
],

[
    "name" => "Coffee Lovers",
    "address" => "Av. Rivadavia 4950, Caballito",
    "lat" => -34.618014,
    "lng" => -58.436221,
    "description" => "Café moderno ideal para trabajar, con enchufes y mesas amplias.",
    "average_rating" => 4.4,
    "opening_hours" => json_encode([
        "lunes" => "08:00-22:00",
        "martes" => "08:00-22:00",
        "miercoles" => "08:00-22:00",
        "jueves" => "08:00-22:00",
        "viernes" => "08:00-23:00",
        "sabado" => "09:00-23:00",
        "domingo" => "09:00-21:00",
    ]),
    "coffee_types" => json_encode(["Colombiano","Etiopé"]),
    "milk_options" => json_encode(["Avena","Sin lactosa"]),
    "features" => json_encode(["wifi","terraza"]),
],

[
    "name" => "Ol' Days Coffee",
    "address" => "Costa Rica 4827, Palermo",
    "lat" => -34.587121,
    "lng" => -58.432722,
    "description" => "Café estilo brunch australiano con ambiente cálido y moderno.",
    "average_rating" => 4.6,
    "opening_hours" => json_encode([
        "lunes" => "09:00-19:00",
        "martes" => "09:00-19:00",
        "miercoles" => "09:00-19:00",
        "jueves" => "09:00-19:00",
        "viernes" => "09:00-20:00",
        "sabado" => "09:00-20:00",
        "domingo" => "09:00-18:00",
    ]),
    "coffee_types" => json_encode(["Guatemalteco","Blend Propietario"]),
    "milk_options" => json_encode(["Avena","Soja"]),
    "features" => json_encode(["wifi","pet_friendly"]),
],

[
    "name" => "Café Crespin",
    "address" => "Vera 699, Villa Crespo",
    "lat" => -34.597832,
    "lng" => -58.438917,
    "description" => "Clásico lugar de brunch con excelente café y panadería artesanal.",
    "average_rating" => 4.5,
    "opening_hours" => json_encode([
        "lunes" => "09:00-19:00",
        "martes" => "09:00-19:00",
        "miercoles" => "09:00-19:00",
        "jueves" => "09:00-19:00",
        "viernes" => "09:00-20:00",
        "sabado" => "09:00-20:00",
        "domingo" => "09:00-19:00",
    ]),
    "coffee_types" => json_encode(["Colombiano"]),
    "milk_options" => json_encode(["Avena","Almendra"]),
    "features" => json_encode(["wifi","musica"]),
],

[
    "name" => "Blue Bagel Co.",
    "address" => "Baez 700, Las Cañitas",
    "lat" => -34.563770,
    "lng" => -58.434887,
    "description" => "Café y bagels artesanales con excelente ambiente.",
    "average_rating" => 4.4,
    "opening_hours" => json_encode([
        "lunes" => "08:30-20:00",
        "martes" => "08:30-20:00",
        "miercoles" => "08:30-20:00",
        "jueves" => "08:30-20:00",
        "viernes" => "08:30-21:00",
        "sabado" => "09:00-21:00",
        "domingo" => "09:00-19:00",
    ]),
    "coffee_types" => json_encode(["Blend Propietario"]),
    "milk_options" => json_encode(["Soja","Avena"]),
    "features" => json_encode(["wifi"]),
],


        ];

        foreach ($cafes as $c) {
            Cafe::create($c);
        }
    }
}
